In [1]:
import tensorflow as tf
import numpy as np
import random
import copy

In [2]:
print(tf.__version__)

2.3.1


## [순서 바꾸기]

(100, 3, 256, 256) <-> (100, 256, 256, 3)

In [3]:
tfdata = tf.random.uniform([100,3,256,256], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,3,256,256)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 3, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 3, 256, 256)
<class 'numpy.ndarray'>


In [4]:
# change 2nd and 4th axis
tfdata = tf.transpose(tfdata, [0, 3, 2, 1])
npdata = np.moveaxis(npdata, 1, -1)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 256, 256, 3)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 256, 256, 3)
<class 'numpy.ndarray'>


In [5]:
# rechange 4th and 2nd axis
tfdata = tf.transpose(tfdata, [0, 3, 2, 1])
npdata = np.moveaxis(npdata, -1, 1)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 3, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 3, 256, 256)
<class 'numpy.ndarray'>


## [차원 늘리기/줄이기]

(100, 100) -> (1, 100, 100) / (100, 1, 100) 

/ (100, 100, 1) -> (100, 100)

In [6]:
tfdata = tf.random.uniform([100,100], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,100)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 100)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 100)
<class 'numpy.ndarray'>


In [7]:
# expand dimension (axis=0,1,2)
tfdata0 = tf.expand_dims(tfdata, axis=0)
npdata0 = np.expand_dims(npdata, axis=0)
print(tfdata0.shape)
print(type(tfdata0))
print(npdata0.shape)
print(type(npdata0))
tfdata1 = tf.expand_dims(tfdata, axis=1)
npdata1 = np.expand_dims(npdata, axis=1)
print(tfdata1.shape)
print(type(tfdata1))
print(npdata1.shape)
print(type(npdata1))
tfdata2 = tf.expand_dims(tfdata, axis=2)
npdata2 = np.expand_dims(npdata, axis=2)
print(tfdata2.shape)
print(type(tfdata2))
print(npdata2.shape)
print(type(npdata2))

(1, 100, 100)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 100, 100)
<class 'numpy.ndarray'>
(100, 1, 100)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 1, 100)
<class 'numpy.ndarray'>
(100, 100, 1)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 100, 1)
<class 'numpy.ndarray'>


In [8]:
# reduce dimension
tfdata0 = tf.squeeze(tfdata0, axis=0)
npdata0 = np.squeeze(npdata0, axis=0)
print(tfdata0.shape)
print(type(tfdata0))
print(npdata0.shape)
print(type(npdata0))

(100, 100)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 100)
<class 'numpy.ndarray'>


## [데이터 나누기]

(100, 3, 256, 256) -> (100, 1, 256, 256), (100, 1, 256, 256), (100, 1, 256, 256)

(100, 3, 256, 256) -> (100, 3, 256, 128), (100, 3, 256, 128)

In [9]:
tfdata = tf.random.uniform([100,3,256,256], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,3,256,256)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 3, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 3, 256, 256)
<class 'numpy.ndarray'>


In [10]:
# split the tensor along axis=1
split_tf10, split_tf11, split_tf12 = tf.split(tfdata, num_or_size_splits=3, axis=1)
print(split_tf10.shape)
print(split_tf11.shape)
print(split_tf12.shape)

(100, 1, 256, 256)
(100, 1, 256, 256)
(100, 1, 256, 256)


In [11]:
# split the ndarray along axis=1
split_np10, split_np11, split_np12 = np.split(npdata, 3, axis=1)
print(split_np10.shape)
print(split_np11.shape)
print(split_np12.shape)

(100, 1, 256, 256)
(100, 1, 256, 256)
(100, 1, 256, 256)


In [12]:
# split the tensor along axis=3
split_tf30, split_tf31 = tf.split(tfdata, num_or_size_splits=2, axis=3)
print(split_tf30.shape)
print(split_tf31.shape)

(100, 3, 256, 128)
(100, 3, 256, 128)


In [13]:
# split the ndarray along axis=3
split_np30, split_np31 = np.split(npdata, 2, axis=3)
print(split_np30.shape)
print(split_np31.shape)

(100, 3, 256, 128)
(100, 3, 256, 128)


## [데이터 합치기]

(100, 3, 256, 256), (100, 3, 256, 256) -> (100, 6, 256, 256)

(100, 3, 256, 256), (100, 3, 256, 256) -> (200, 3, 256, 256)

(100, 3, 256, 256), (100, 3, 256, 256) -> (100, 3, 256, 512)

In [14]:
tfdata = tf.random.uniform([100,3,256,256], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,3,256,256)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 3, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 3, 256, 256)
<class 'numpy.ndarray'>


In [15]:
# concatenate along axis=1
tfdata1 = tf.concat([tfdata, tfdata], axis=1)
print(tfdata1.shape)
print(type(tfdata1))

(100, 6, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
# concatenate along axis=1
npdata1 = np.concatenate((npdata, npdata), axis=1)
print(npdata1.shape)
print(type(npdata1))

(100, 6, 256, 256)
<class 'numpy.ndarray'>


In [17]:
# concatenate along axis=0
tfdata0 = tf.concat([tfdata, tfdata], axis=0)
print(tfdata0.shape)
print(type(tfdata0))

(200, 3, 256, 256)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [18]:
# concatenate along axis=0
npdata0 = np.concatenate((npdata, npdata), axis=0)
print(npdata0.shape)
print(type(npdata0))

(200, 3, 256, 256)
<class 'numpy.ndarray'>


In [19]:
# concatenate along axis=3
tfdata3 = tf.concat([tfdata, tfdata], axis=3)
print(tfdata3.shape)
print(type(tfdata3))

(100, 3, 256, 512)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [20]:
# concatenate along axis=3
npdata3 = np.concatenate((npdata, npdata), axis=3)
print(npdata3.shape)
print(type(npdata3))

(100, 3, 256, 512)
<class 'numpy.ndarray'>


## [평균값 구하기]

(100, 50, 30) -> (100, 50)

(100, 50, 30) -> (100, 30)

(100, 50, 30) -> (100)

(100, 50, 30) -> 값

In [21]:
tfdata = tf.random.uniform([100,50,30], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,50,30)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 50, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50, 30)
<class 'numpy.ndarray'>


In [22]:
# mean along axis=2
tfm2 = tf.reduce_mean(tfdata, axis=2)
npm2 = np.mean(npdata, axis=2)
print(tfm2.shape)
print(type(tfm2))
print(npm2.shape)
print(type(npm2))

(100, 50)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50)
<class 'numpy.ndarray'>


In [23]:
# mean along axis=1
tfm1 = tf.reduce_mean(tfdata, axis=1)
npm1 = np.mean(npdata, axis=1)
print(tfm1.shape)
print(type(tfm1))
print(npm1.shape)
print(type(npm1))

(100, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 30)
<class 'numpy.ndarray'>


In [24]:
# mean along axis=1 and axis=2
tfm12 = tf.reduce_mean(tfdata, axis=(1,2))
npm12 = np.mean(npdata, axis=(1,2))
print(tfm12.shape)
print(type(tfm12))
print(npm12.shape)
print(type(npm12))

(100,)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100,)
<class 'numpy.ndarray'>


In [25]:
# mean along all axes
tfm = tf.reduce_mean(tfdata)
npm = np.mean(npdata)
print(tfm)
print(type(tfm))
print(npm)
print(type(npm))

tf.Tensor(5.002161, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
0.4998525569330445
<class 'numpy.float64'>


## [max / min 값만 뽑아서 새로운 데이터 만들기]

(100, 50, 30) -> (100, 50)

(100, 50, 30) -> (100, 30)

(100, 50, 30) -> (100)

(100, 50, 30) -> 값

In [26]:
tfdata = tf.random.uniform([100,50,30], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,50,30)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

(100, 50, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50, 30)
<class 'numpy.ndarray'>


In [27]:
# max along axis=2
tfmax2 = tf.reduce_max(tfdata, axis=2)
npmax2 = np.amax(npdata, axis=2)
print(tfmax2.shape)
print(type(tfmax2))
print(npmax2.shape)
print(type(npmax2))

# min along axis=2
tfmin2 = tf.reduce_min(tfdata, axis=2)
npmin2 = np.amin(npdata, axis=2)
print(tfmin2.shape)
print(type(tfmin2))
print(npmin2.shape)
print(type(npmin2))

(100, 50)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50)
<class 'numpy.ndarray'>
(100, 50)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50)
<class 'numpy.ndarray'>


In [28]:
# max along axis=1
tfmax1 = tf.reduce_max(tfdata, axis=1)
npmax1 = np.amax(npdata, axis=1)
print(tfmax1.shape)
print(type(tfmax1))
print(npmax1.shape)
print(type(npmax1))

# min along axis=1
tfmin1 = tf.reduce_min(tfdata, axis=1)
npmin1 = np.amin(npdata, axis=1)
print(tfmin1.shape)
print(type(tfmin1))
print(npmin1.shape)
print(type(npmin1))

(100, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 30)
<class 'numpy.ndarray'>
(100, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 30)
<class 'numpy.ndarray'>


In [29]:
# max along axis=1 and axis=2
tfmax12 = tf.reduce_max(tfdata, axis=(1,2))
npmax12 = np.amax(npdata, axis=(1,2))
print(tfmax12.shape)
print(type(tfmax12))
print(npmax12.shape)
print(type(npmax12))

# min along axis=1 and axis=2
tfmin12 = tf.reduce_min(tfdata, axis=(1,2))
npmin12 = np.amin(npdata, axis=(1,2))
print(tfmin12.shape)
print(type(tfmin12))
print(npmin12.shape)
print(type(npmin12))

(100,)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100,)
<class 'numpy.ndarray'>
(100,)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100,)
<class 'numpy.ndarray'>


In [30]:
# max along all axes
tfmax = tf.reduce_max(tfdata)
npmax = np.amax(npdata)
print(tfmax)
print(type(tfmax))
print(npmax)
print(type(npmax))

# min along all axes
tfmin = tf.reduce_min(tfdata)
npmin = np.amin(npdata)
print(tfmin)
print(type(tfmin))
print(npmin)
print(type(npmin))

tf.Tensor(9.999848, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
0.9999906193819845
<class 'numpy.float64'>
tf.Tensor(0.00019431114, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
1.3829718211955111e-05
<class 'numpy.float64'>


## [index 목록을 가지고 one-hot 형태의 데이터 만들기]

[1, 3, 2, 5, 0, 7, 8] -> (7, 10): (length of list, dimension size)

In [31]:
idx = [1,3,2,5,0,7,8]

tfonehot = tf.one_hot(idx, 10)
tfonehot.shape
print(tfonehot)

tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]], shape=(7, 10), dtype=float32)


## [max / min 값에 해당하는 값만 1을 가지고 나머지는 0을 가지는 one-hot 형태의 데이터 만들기]

(100, 50, 30) -> (100, 50, 30)

In [32]:
tfdata = tf.random.uniform([100,50,30], minval=0, maxval=10, seed=42)
npdata = np.random.rand(100,50,30)
print(tfdata.shape)
print(type(tfdata))
print(npdata.shape)
print(type(npdata))

tfmax2 = tf.math.argmax(tfdata, axis=2)
tfonehot = tf.zeros_like(tfdata)
npmax2 = np.argmax(npdata, axis=2)
nponehot = np.zeros_like(npdata)

# only for tensor type data
onehot = np.array(tfonehot)

for i in range(100):
    for j in range(50):
        onehot[i][j][tfmax2[i][j]] = 1
        
for i in range(100):
    for j in range(50):
        nponehot[i][j][npmax2[i][j]] = 1

print(onehot.shape)
print(onehot[0][0])
print(nponehot.shape)
print(nponehot[0][0])

(100, 50, 30)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(100, 50, 30)
<class 'numpy.ndarray'>
(100, 50, 30)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0.]
(100, 50, 30)
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


## [one-hot 형태의 데이터를 이용해서, 다른 데이터에 있는 값중 one-hot에서 1에 해당하는 위치의 값만을 가져오기]

A: (100, 50, 30) - onehot, 

B: (100, 50, 30) -> (100, 50, 1)

In [33]:
# onehot type data
A_tf = onehot
A_np = nponehot

# another data with same shape
B_tfdata = tf.random.uniform([100,50,30], minval=0, maxval=10, seed=42)
B_npdata = np.random.rand(100,50,30)

tfdata = tf.zeros_like(B_tfdata)
# convert tensor type data to ndarray type data
tfdata = np.array(tfdata)
tfdata = np.resize(tfdata, (100,50,1))

npdata = np.zeros_like(B_npdata)
npdata = np.resize(npdata, (100,50,1))

for i in range(100):
    for j in range(50):
        tfdata[i][j] = B_tfdata[i][j][tf.math.argmax(A_tf, axis=2)[i][j]]
        
for i in range(100):
    for j in range(50):
        npdata[i][j] = B_npdata[i][j][np.argmax(A_np,axis=2)[i][j]]
        
print(tfdata.shape)
print(npdata.shape)

(100, 50, 1)
(100, 50, 1)


## [one-hot 형태의 데이터를 이용해서, 다른 데이터에 있는 값중 one-hot에서 1에 해당하는 위치의 값만 남기고 나머지는 0으로 만들기]

A: (100, 50, 30) - onehot, 

B: (100, 50, 30) -> (100, 50, 30)

In [34]:
# onehot type data
A_tf = onehot
A_np = nponehot

# another data with same shape
B_tfdata = tf.random.uniform([100,50,30], minval=0, maxval=10, seed=42)
B_npdata = np.random.rand(100,50,30)

tfdata = A_tf * B_tfdata
npdata = A_np * B_npdata
print(tfdata.shape)
print(npdata.shape)

(100, 50, 30)
(100, 50, 30)
